### ISSUE TITLE
Релиз v3.0.0

### ISSUE THREAD

**Issue by fonrit** [tinkoff-mobile-tech/tinkoff-asdk-android#220]
Ожидать ли в конце Q1 2023 релиз v3.0.0 ?

**Comment by jQwout** [comment]
Здравствуйте, ожидаемый срок - конец марта\начала апреля.(то есть уже почти все сделали , см ветку v3.0.0
Пожайлуста, напомните, какие фичи вы бы хотели увидеть, мы постараемся про них не забыть.

**Comment by fonrit** [comment]
1) Возможность обработки результата через rememberLauncherForActivityResult для compose
2) Навигация для экрана 3ds
3) Автоподстановка кода из пуша на экране 3ds
4) Добавить признак типа перевода после совершения транзакции (По номеру карты или сбп)

Можете еще подсказать, планируется ли доработка рекуррентных списаний при переводе через сбп ?

**Comment by jQwout** [comment]
Здравствуйте!

1. да, в работе, как будет сделано, можно посмотреть драфт в 3.0.0
2. Вы имеете ввиду, тулбар на вебвью? можем взять в версию.
3. Cложный кейс, нет понимания , как вставить текст в вебвью на строне 3дс. можем подумать про это , когда подключим app-base 3ds флоу.
4. Да, контракты успеха-завершения платежей находятся на перерабортке, учтем ваще пожелание!
5. У нас в планах на 3.0.0 такого не было, рекурентный платеж осуществляется только по карте.

**Comment by stakancheck** [comment]
@jQwout что там с релизом? Подскажите, стоит ли ждать до июня или интегрировать текущую версию?

**Comment by harcoPro** [comment]
@stakancheck Добрый день.
Релиз будет после 8 июня.

**Comment by stakancheck** [comment]
@harcoPro подскажете, пожалуйста, текущую информацию о готовности 3 версии!

**Comment by fonrit** [comment]
@harcoPro можете подсказать где можно ознакомиться с кратким содержанием релиза **v3.0.0** из важного (изменения контрактов, доработки и т.д) как я понимаю он уже на финишной прямой, очень ждем!

**Comment by harcoPro** [comment]
@stakancheck Добрый день!
Ориентировочно на след. неделе

**Comment by harcoPro** [comment]
@fonrit Добрый день!
Можете ознакомиться с предварительным чейнджлогом в ветке [MC-8269_new_docs](https://github.com/tinkoff-mobile-tech/AcquiringSdkAndroid/tree/MC-8269_new_docs)

**Comment by TheFoxKD** [comment]
Добрый день!
Подскажите, пожалуйста, когда релиз состоится?

**Comment by harcoPro** [comment]
Добрый день!
Точную дату не могу сказать, но в текущий момент идет тестирование.

**Comment by harcoPro** [comment]
Релиз состоялся.
